baseURL = 'https://sylvain-bauvais.fr/'
title = 'Sylvain Bauvais'
languageCode = 'fr-fr'
copyright = "© 2022 Sylvain Bauvais"
enableRobotsTXT = true
PygmentsStyle = "dracula"
defaultContentLanguage = "fr"
disableKinds = ["taxonomy", "term"]
timeZone = "Europe/Paris"

[params]
  description = "UI/UX designer & intégrateur freelance à Lille. Création ou refonte de sites vitrine, e-commerce et design d'interfaces web et mobile."
  author = "Sylvain Bauvais"
  twitter = "/twitter-card.png"
  feedDescription = "Réflexions et tutoriels sur l’UX/UI design, les outils et la technologie."
  cover = "/og-cover.png"

[markup]
  [markup.goldmark] 
    [markup.tableOfContents]
        endLevel = 2
        ordered = false
    [markup.goldmark.renderer]
        unsafe= true